### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#123]
It's time for Pup to grow up. As we move forward, releases will need to be consistently stable. @pilarArr is actively researching testing strategies, but as part of our move to having tests in Pup, we should look to have CI in place for the project.

**Comment by cleverbeagle** [comment]
Documenting @merlinpatt's refined version of this:

```
defaults: &defaults
  working_directory: /tmp/workspace
  docker:
    - image: circleci/node:8.11.3

branches_list: &branches_list
  - master
  - 2.0.0
  - /feature\/.*/
  - /refactor\/.*/
  - /bug\/.*/
  - /chore\/.*/

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - run: ls /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ./*
      - save_cache:
          paths:
            - node_modules
            - ~/.meteor
            - ~/.npm
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: curl https://install.meteor.com | /bin/sh

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls /tmp/workspace
      - run: npm run lint

  test_unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: meteor npm test

  test_e2e:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: meteor npm run dev
          background: true
      - run: sleep 100 # Wait for app to run before starting e2e tests.
      - run: meteor npm run test-e2e

workflows:
  version: 2
  build_and_lint:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - 2.0.0
                - /feature\/.*/
                - /refactor\/.*/
                - /bug\/.*/
                - /chore\/.*/
      - lint:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - 2.0.0
                - /feature\/.*/
                - /refactor\/.*/
                - /bug\/.*/
                - /chore\/.*/
```
