### ISSUE TITLE
Move resend verification email into its own component

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#46]
Just noticed this. The process adds just enough boilerplate to the `<App />` component that it'd be nice to just have a `<VerifyEmailAlert />` component.

**Comment by cleverbeagle** [comment]
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import { Alert, Button } from 'react-bootstrap';
import { Meteor } from 'meteor/meteor';
import { Bert } from 'meteor/themeteorchef:bert';

const handleResendVerificationEmail = (emailAddress) => {
  Meteor.call('users.sendVerificationEmail', (error) => {
    if (error) {
      Bert.alert(error.reason, 'danger');
    } else {
      Bert.alert(`Check ${emailAddress} for a verification link!`, 'success');
    }
  });
};

const VerifyEmailAlert = ({ userId, emailVerified, emailAddress }) => (
  userId && !emailVerified ? (
    <div className="VerifyEmailAlert">
      <Alert className="verify-email text-center">
        <p>Hey friend! Can you <strong>verify your email address</strong> ({emailAddress}) for us?
          <Button
            bsStyle="link"
            onClick={() => handleResendVerificationEmail(emailAddress)}
            href="#"
          >
            Re-send verification email
          </Button>
        </p>
      </Alert>
    </div>
  ) : null
);

VerifyEmailAlert.propTypes = {
  userId: PropTypes.string.isRequired,
  emailVerified: PropTypes.bool.isRequired,
  emailAddress: PropTypes.string.isRequired,
};

export default VerifyEmailAlert;
```

SCSS

```scss
@import '../../stylesheets/colors';

.VerifyEmailAlert {
  margin-bottom: 0;
  padding: 0;
  border-top: none;
  border-bottom: 1px solid #e7e7e7;
  background: #fff;
  color: $gray-dark;
  border-radius: 0;

  p {
    padding: 19px;
  }

  .btn {
    padding: 0;
  }
}
```
